services:
    db:
        container_name: event_manager_postgres_db
        image: postgres:15.8
        restart: unless-stopped
        hostname: localhost
        environment:
            POSTGRES_DB: event_manager
            POSTGRES_PASSWORD: 2137
            POSTGRES_USER: postgres
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    pgdata:
